### ISSUE TITLE
Command check should be optimized with switch statements

### ISSUE THREAD

**Issue by aqariio** [OoEthanoO/Task-Manager#1]
if (command == "showCommands") {
                showCommands();
            } else if (command == "version") {
                version();
            } else if (command == "add") {
                add();
            } else if (command == "exit") {
                exitProgram();
            } else if (command == "clear") {
                clear();
            } else if (command == "display") {
                display();
            } else if (command == "remove") {
                remove();
            }

**Comment by OoEthanoO** [comment]
ok

**Comment by OoEthanoO** [comment]
good suggestion, i'll change it later

**Comment by aqariio** [comment]
#2
